### ISSUE TITLE
Is SexLab Dialogues really blocking some quests?

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#224]
Some users reported potential issue with:

- dialogue to buy Proudspire manor
- dialogues to start Animal Mansion quest
- Bestial Essence topics
- dialogues from Interesting NPCs

**Comment by SkyrimLL** [comment]
So far, nothing indicates SexLab Dialogues can block other quests.

I reduced the priority of the topics just in case.

More investigation needed.

**Comment by volfin** [comment]
I've experienced the blocking of Animal Mansion. Was only when Sexlab Dialogs was removed that the missing dialog options appeared. I've also seen it block some dialog options for Maria Eden.  I have a theory, (untested) that it's because of the sheer # of options SLD adds. I already have many other mods adding extra dialog options, so when SLD adds another 10 or more options, maybe it goes over some limit (sometimes I have 20-30 options at a time) But I'm really in no position to test at this point.

**Comment by SkyrimLL** [comment]
Again... do you have a precise example of missing dialogue when SL Dialogues is enabled?
Which NPC should I talk to? What should I expect to see in the dialogue topics that is not there?
I need a repeatable example to test things if we want to get to the bottom of this issue.

**Comment by volfin** [comment]
As I said, I'm not able to change my whole skyrim setup just to find this for you at this time. But it's was glaringly obvious when you enter the Animal Mansion, and you were unable to start the main questline because the owner of the mansion has no dialogs to start the quest.  It was only when SDialog was removed that her dialogs to start the quest appears.  It should be extremely easy to find since you can't even start the main quest with SDialogs installed.

**Comment by SkyrimLL** [comment]
@volfin - That's the thing - When I tried Animal Mansion with Dialogues on, I was able to talk to the owner and get started on her first quest.

So I still need more details on that one :)

So far, the most detailed report about this issue was for an NPC from Interesting NPCs missing his dialogues and for that one too, I was able to view his dialogues with SL Dialogues on (someone else confirmed it was working for him too).

I am not saying it is not SL Dialogue's fault yet... just that it looks like I need more details to reproduce it on my end.

**Comment by ContentConsumer** [comment]
I have run through Animal Mansion several times, both with and without Dialogues installed, with Dialogues both above and below the load order. I have never had an issue like this.

I'm not totally certain this is Dialogues at all...
