### ISSUE TITLE
Missing dialogues with master on Falmer enslavement

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#39]
Sometimes, dialogue topics with (Falmer) Master are not clickable anymore.
Reloading the game seems to fix it.

**Comment by SkyrimLL** [comment]
Could be a scene running on the master, with a long time out value.
Need to find out what is triggering it.

**Comment by ContentConsumer** [comment]
I have noticed this problem happening with other mods - dialogue just stays there as if you can click it, but nothing happens when you do.
I believe it has something to do with a sex scene interrupting a running quest somehow... a long-running conversation was stopped dead midway because the Sexlife mod had triggered sex with the target.

You might contact DocClox with this issue, I believe he's having a similar problem.

**Comment by bicobus** [comment]
Bumpy bump.

Is this issue still relevant?

**Comment by SkyrimLL** [comment]
Indeed it is not .. thanks for tellin gme.
Same as issue #657 - closing.
