### ISSUE TITLE
options not showing up

### ISSUE THREAD

**Issue by TMiner99** [SkyrimLL/SDPlus#787]
i don't know if there's a conflict with devious followers or devious helpers and SD+ but i can't see all but one option

i have the latest version and i have led a play through with completion to lvl 6

i also disabled these mods and reinstalled SD+, but it still shows one option.
here's the papyrus log and i put a similar post under loverslab
![20180420100452_1](https://user-images.githubusercontent.com/13771413/39079176-691d6c46-44ca-11e8-9cee-fa998bd82fd1.jpg)
this one is  a follower not following me ( all npcs show the one option)

![20180420101300_1](https://user-images.githubusercontent.com/13771413/39079188-a1fcfb1c-44ca-11e8-96e0-32a655440f3a.jpg)
![20180420101303_1](https://user-images.githubusercontent.com/13771413/39079191-a711588c-44ca-11e8-96c8-dfa0530da2e7.jpg)
this is having a active follower owner

[Papyrus.0.log](https://github.com/SkyrimLL/SDPlus/files/1934047/Papyrus.0.log)

**Comment by SkyrimLL** [comment]
Thanks for the report... somehow I did not see it until now.

I noticed in some occasions the Master? dialogue is not showing. This can happen sometimes with Sanguine. I am not sure how it is happening though, so I am afraid I cannot help in this case. It seems to be possibly caused by conflicting parameters, as in a friendly/follower NPC becoming your owner.

**Comment by SkyrimLL** [comment]
This should be working now.
I fixed several issues in the latest version of 2018, including an issue with main dialogues not showing with masters.
