### ISSUE TITLE
Not able to enable the mod

### ISSUE THREAD

**Issue by Skeletim13** [SkyrimLL/SDPlus#851]
Hi, I can't enable the mod. Everything on the "Status" screen is grayed out.

**Comment by SkyrimLL** [comment]
The mod should enable itself automatically. What happens sometimes is that people start playing with it right away instead of saving and reloading it to initialize it properly.

Look at the first question in the FAQ for tips about how to initialize it properly - https://github.com/SkyrimLL/SDPlus/wiki/FAQ
