### ISSUE TITLE
crashes at random

### ISSUE THREAD

**Issue by warmsusu** [SkyrimLL/SDPlus#865]
when I play like 20 mins at random sometimes I crash im pretty sure its this mod it only happens if im wearing a collar or when a owner was rushing me ,the master was a random bandit by whiterun

**Comment by SkyrimLL** [comment]
Skyrim can crash for so many reasons... without an error log or more details, I am afraid there is nothing I can do about your issue.

Please report this kind of issue to the forum itels and not here so that other people can see it and comment.

https://www.loverslab.com/topic/24042-sd-sanguine-debauchery-enhanced-2018-12-20/
